
version: '3.9'
volumes:
  postgres_data:
  static:
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ezrawick/infra-sp2:latest
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static:/static
      - ./etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web