 
version: '3.7'
volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ezrawick/infra-sp2
    restart: always
    command: python manage.py collectstatic --noinput && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - /static:/static
    expose:
      - "8000"
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web